/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — touches no dependency */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — checks dependencies */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin OIDC authorization code + PKCE
         * @description 307 the browser to the IdP's **public** issuer.
         *
         *     `RedirectResponse` defaults to 307 and the method is GET either way, so no
         *     body is at stake.
         *
         *     A denial here — unknown org, disabled provider, an org whose default is a
         *     password provider — sends the browser back to the sign-in screen rather than
         *     rendering a JSON 401 at it. See the module docstring: the answer is one
         *     constant either way, and the caller is a browser.
         */
        get: operations["oidc_authorize_api_v1_auth_oidc_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OIDC callback: open a session and return the browser to the app
         * @description Verify `state`, exchange `code` server-side, validate the token, open a session.
         *
         *     M3.3 ended here with a `SubjectResponse` — proof that a login *happened*,
         *     with no way to stay logged in. M3.4 made it a token pair in a JSON body,
         *     which is right for a test client and wrong for the only caller it has: this
         *     endpoint is reached by a top-level navigation from Keycloak, so a JSON body
         *     is a page of text rendered at a person who expected an application.
         *
         *     It therefore sets the refresh cookie and redirects, **carrying no token in
         *     the URL**. The page it lands on exchanges the cookie for an access token.
         *
         *     `error` is what the IdP sends when the user cancels or is refused. It is a
         *     denial like any other and is never echoed back: the IdP's error strings are
         *     diagnostic and can name internal configuration.
         */
        get: operations["oidc_callback_api_v1_auth_oidc_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current principal, resolved against the live database
         * @description The first route in the system that is **not** in the public allow-list.
         *
         *     It declares no guard of its own — `require_caller` only *reads* the identity
         *     the application-level dependency already resolved — which is the whole point:
         *     being authenticated is what a route gets for doing nothing.
         */
        get: operations["read_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new access token
         * @description Rotate the refresh token and mint a fresh access token.
         *
         *     **Every call rotates.** The token that came in is retired and a new one goes
         *     out on the cookie; presenting the retired one again revokes the entire chain,
         *     because at that point two parties hold copies of one credential and nothing
         *     here can tell which one is the thief.
         *
         *     The practical consequence for a client is that *concurrent* refreshes are
         *     indistinguishable from theft and must be collapsed into one in-flight call.
         *     That is the frontend half of M3.4 and it is written down in TRACKER §5.
         */
        post: operations["issue_token_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token:revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token and its whole rotation chain
         * @description Sign out. **Always 204**, whatever was presented.
         *
         *     RFC 7009 §2.2 asks for the same, and the reason is worth stating: an endpoint
         *     that answers 401 for an unknown token and 204 for a known one is a free oracle
         *     for testing stolen credentials — and the caller is unauthenticated, because
         *     presenting the token *is* the authentication. So unknown, expired, malformed
         *     and absent all get one answer, and the cookie is cleared either way rather
         *     than leaving a client holding a credential it believes it revoked.
         */
        post: operations["revoke_token_api_v1_auth_token_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_chat_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_v1_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Rename Session */
        patch: operations["rename_session_api_v1_chat_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_chat_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["list_folders_api_v1_chat_folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_api_v1_chat_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Folder */
        delete: operations["delete_folder_api_v1_chat_folders__folder_id__delete"];
        options?: never;
        head?: never;
        /** Update Folder */
        patch: operations["update_folder_api_v1_chat_folders__folder_id__patch"];
        trace?: never;
    };
    "/api/v1/chat/messages/{message_id}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Bookmark */
        put: operations["upsert_bookmark_api_v1_chat_messages__message_id__bookmark_put"];
        post?: never;
        /** Remove Bookmark */
        delete: operations["remove_bookmark_api_v1_chat_messages__message_id__bookmark_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookmarks */
        get: operations["list_bookmarks_api_v1_chat_bookmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages/{message_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Feedback */
        put: operations["upsert_feedback_api_v1_chat_messages__message_id__feedback_put"];
        post?: never;
        /** Remove Feedback */
        delete: operations["remove_feedback_api_v1_chat_messages__message_id__feedback_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_knowledge_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_knowledge_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_knowledge_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_knowledge_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_connectors_get"];
        put?: never;
        /** Register Source */
        post: operations["register_source_api_v1_connectors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_connectors_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_connectors_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{slug}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_connectors__slug__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{slug}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Item
         * @description Enqueue a `queued` `ingest_job` for one item the source currently
         *     lists — the second producer `entrypoints/worker/main.py`'s docstring
         *     already anticipated. Refuses a `uri` the source does not currently list,
         *     same discipline `mnemosctl connector ingest` enforces, so this can never
         *     become an arbitrary-fetch primitive for a slug the caller's org owns.
         */
        post: operations["ingest_item_api_v1_connectors__slug__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Servers */
        get: operations["list_servers_api_v1_tools_servers_get"];
        put?: never;
        /** Register Server */
        post: operations["register_server_api_v1_tools_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/servers/{server_id}/credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Credential */
        put: operations["save_credential_api_v1_tools_servers__server_id__credential_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/servers/{server_id}/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Tools */
        post: operations["discover_tools_api_v1_tools_servers__server_id__discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{tool_id}/grants/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant Tool To Self */
        post: operations["grant_tool_to_self_api_v1_tools__tool_id__grants_self_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invocations */
        get: operations["list_invocations_api_v1_tools_invocations_get"];
        put?: never;
        /** Propose Invocation */
        post: operations["propose_invocation_api_v1_tools_invocations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/invocations/{invocation_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Invocation */
        post: operations["approve_invocation_api_v1_tools_invocations__invocation_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/invocations/{invocation_id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deny Invocation */
        post: operations["deny_invocation_api_v1_tools_invocations__invocation_id__deny_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memory History */
        get: operations["list_memory_history_api_v1_memories_get"];
        put?: never;
        /** Create Memory */
        post: operations["create_memory_api_v1_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories/{memory_id}/supersede": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Supersede Memory */
        post: operations["supersede_memory_api_v1_memories__memory_id__supersede_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memories/{memory_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract Memory */
        post: operations["retract_memory_api_v1_memories__memory_id__retract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context/messages/{message_id}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Message Bundle */
        get: operations["get_message_bundle_api_v1_context_messages__message_id__bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_knowledge_documents_post */
        Body_upload_document_api_v1_knowledge_documents_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
        };
        /** BookmarkListResponse */
        BookmarkListResponse: {
            /** Bookmarks */
            bookmarks: components["schemas"]["BookmarkedMessageResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** BookmarkResponse */
        BookmarkResponse: {
            /** Id */
            id: string;
            /** Message Id */
            message_id: string;
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string;
        };
        /** BookmarkedMessageResponse */
        BookmarkedMessageResponse: {
            /** Id */
            id: string;
            /** Message Id */
            message_id: string;
            /** Session Id */
            session_id: string;
            /** Session Title */
            session_title: string;
            /** Message Role */
            message_role: string;
            /** Message Content */
            message_content: string;
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string;
        };
        /** BundleItemResponse */
        BundleItemResponse: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Section */
            section: string;
            /** Operator */
            operator: string;
            /** Text */
            text: string;
            /** Tokens */
            tokens: number;
            /** Raw Score */
            raw_score: number;
            /** Rrf Score */
            rrf_score: number;
            /** Utility */
            utility: number;
            /** Density */
            density: number;
            /** Trust Tier */
            trust_tier: number;
            /** Source Kind */
            source_kind: string;
            /** Source Ref */
            source_ref: string;
            /** Document Title */
            document_title: string | null;
            /** Acl Rule */
            acl_rule: string;
            /** Memory Id */
            memory_id: string | null;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            /** Id */
            id: string;
            /** Ordinal */
            ordinal: number;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Flow */
            flow: string | null;
            /** Router Rationale */
            router_rationale: string | null;
            /** Bundle Id */
            bundle_id: string | null;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Latency Ms */
            latency_ms: number | null;
            /** Model */
            model: string | null;
            /** Finish Reason */
            finish_reason: string | null;
            /** Created At */
            created_at: string;
            /** Bookmarked */
            bookmarked: boolean;
            /** Feedback */
            feedback: ("up" | "down") | null;
        };
        /** ChatSessionDetailResponse */
        ChatSessionDetailResponse: {
            session: components["schemas"]["ChatSessionResponse"];
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
            /** Citations */
            citations: components["schemas"]["CitationResponse"][];
        };
        /** ChatSessionListResponse */
        ChatSessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["ChatSessionResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ChatSessionResponse */
        ChatSessionResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Is Archived */
            is_archived: boolean;
            /** Folder Id */
            folder_id: string | null;
            /** Last Message At */
            last_message_at: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** CitationResponse */
        CitationResponse: {
            /** Id */
            id: string;
            /** Message Id */
            message_id: string;
            /** Marker */
            marker: number;
            /** Document Id */
            document_id: string | null;
            /** Chunk Id */
            chunk_id: string | null;
            /** Quoted Text */
            quoted_text: string;
            /** Start Char */
            start_char: number | null;
            /** End Char */
            end_char: number | null;
            /** Page Number */
            page_number: number | null;
            /** Score */
            score: number | null;
        };
        /** ContextBundleResponse */
        ContextBundleResponse: {
            /** Id */
            id: string;
            /** Digest */
            digest: string;
            /** Flow */
            flow: string;
            /** Token Budget */
            token_budget: number;
            /** Tokens Consumed */
            tokens_consumed: number;
            /** Compiled Prompt */
            compiled_prompt: string;
            /** Budget Report */
            budget_report: {
                [key: string]: unknown;
            };
            /** Explain */
            explain: {
                [key: string]: unknown;
            };
            /** Admitted */
            admitted: components["schemas"]["BundleItemResponse"][];
            /** Rejections */
            rejections: components["schemas"]["RejectionResponse"][];
            /** Lineage */
            lineage: components["schemas"]["LineageResponse"][];
            /** Created At */
            created_at: string;
        };
        /** CreateFolderRequest */
        CreateFolderRequest: {
            /** Name */
            name: string;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Title */
            title?: string | null;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Media Type */
            media_type: string;
            /** Byte Size */
            byte_size: number;
            /** Status */
            status: string;
            /** Superseded By */
            superseded_by: string | null;
            /** Chunk Count */
            chunk_count: number;
            /** Created At */
            created_at: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Id */
            id: string;
            /** Message Id */
            message_id: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
            /** Comment */
            comment: string | null;
            /** Created At */
            created_at: string;
        };
        /** FolderListResponse */
        FolderListResponse: {
            /** Folders */
            folders: components["schemas"]["FolderResponse"][];
        };
        /** FolderResponse */
        FolderResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Session Count */
            session_count: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** GrantResponse */
        GrantResponse: {
            /** Id */
            id: string;
            /** Tool Id */
            tool_id: string;
            /** User Id */
            user_id: string;
            /** Auto Approve */
            auto_approve: boolean;
            /** Expires At */
            expires_at: string | null;
        };
        /** GrantSelfRequest */
        GrantSelfRequest: {
            /**
             * Auto Approve
             * @default false
             */
            auto_approve: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestJobEventResponse */
        IngestJobEventResponse: {
            /** Id */
            id: string;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string;
            /** Owner Id */
            owner_id: string | null;
            /** Detail */
            detail: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** IngestJobResponse */
        IngestJobResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Payload */
            payload: {
                [key: string]: string;
            };
            /** Document Id */
            document_id: string | null;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Done Units */
            done_units: number;
            /** Total Units */
            total_units: number;
            /** Owner Id */
            owner_id: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Events */
            events: components["schemas"]["IngestJobEventResponse"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /** Uri */
            uri: string;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Uri */
            uri: string;
        };
        /** InvocationResponse */
        InvocationResponse: {
            /** Id */
            id: string;
            /** Tool Id */
            tool_id: string;
            /** User Id */
            user_id: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Caller Trust Tier */
            caller_trust_tier: number;
            /** Denied Reason */
            denied_reason: string | null;
            /** Offending Source */
            offending_source: string | null;
            /** Approved By */
            approved_by: string | null;
            /** Approved At */
            approved_at: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Code */
            error_code: string | null;
            /** Created At */
            created_at: string;
        };
        /** ItemResponse */
        ItemResponse: {
            /** Uri */
            uri: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Content Type */
            content_type: string;
            /** Modified At */
            modified_at: string | null;
        };
        /** LineageResponse */
        LineageResponse: {
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /** Kind */
            kind: string;
            /** Rationale */
            rationale: string | null;
        };
        /**
         * MeResponse
         * @description Who the bearer of this access token is, resolved against the live database.
         *
         *     **Every field here was read on this request, not carried in the token.** The
         *     token names a user, an org and a session and says nothing about authority
         *     (`domain/token.py`), so `permissions` and `tags` are the repository's answer
         *     a moment ago rather than the IdP's answer at login. That is what makes a
         *     revoked role take effect on the next call instead of in fifteen minutes, and
         *     it is observable here: mint a token, change a binding, call this again.
         *
         *     `permissions` is reported, not enforced. The permission matrix — requiring a
         *     concrete `resource:action` per route — is a later milestone; listing the
         *     grants is how the shell knows what to offer, and hiding a control is a
         *     courtesy rather than the control itself.
         */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Org Id */
            org_id: string;
            /** Org Slug */
            org_slug: string;
            /** Session Id */
            session_id: string;
            /**
             * Permissions
             * @description Effective `resource:action` grants, live
             */
            permissions: string[];
            /**
             * Tags
             * @description Tag slugs this principal can reach (constraint C4)
             */
            tags: string[];
        };
        /** MemoryEdgeResponse */
        MemoryEdgeResponse: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /** Kind */
            kind: string;
            /** Rationale */
            rationale: string | null;
            /** Created At */
            created_at: string;
        };
        /** MemoryHistoryResponse */
        MemoryHistoryResponse: {
            /** Claims */
            claims: components["schemas"]["MemoryResponse"][];
            /** Edges */
            edges: components["schemas"]["MemoryEdgeResponse"][];
        };
        /** MemoryResponse */
        MemoryResponse: {
            /** Id */
            id: string;
            subject: components["schemas"]["MemorySubjectResponse"];
            /** Predicate */
            predicate: string;
            /** Object Text */
            object_text: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Scope */
            scope: {
                [key: string]: string;
            };
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to: string;
            /** Recorded At */
            recorded_at: string;
            /** Retracted At */
            retracted_at: string | null;
            /** Confidence */
            confidence: number;
            /** Trust Tier */
            trust_tier: number;
            /** Source Kind */
            source_kind: string;
            /** Source Ref */
            source_ref: string | null;
        };
        /** MemorySubjectResponse */
        MemorySubjectResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** External Ref */
            external_ref: string;
            /** Display Name */
            display_name: string;
        };
        /** MemoryWriteRequest */
        MemoryWriteRequest: {
            /** Subject Kind */
            subject_kind: string;
            /** Subject Ref */
            subject_ref: string;
            /** Subject Name */
            subject_name: string;
            /** Predicate */
            predicate: string;
            /** Object Text */
            object_text: string;
            /**
             * Kind
             * @default fact
             * @enum {string}
             */
            kind: "fact" | "preference" | "decision" | "observation";
            /** Scope */
            scope?: {
                [key: string]: string;
            };
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** MemoryWriteResponse */
        MemoryWriteResponse: {
            claim: components["schemas"]["MemoryResponse"];
            /** Superseded */
            superseded: string[];
        };
        /** ProposeInvocationRequest */
        ProposeInvocationRequest: {
            /** Tool Id */
            tool_id: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Offending Bundle Item Id */
            offending_bundle_item_id?: string | null;
        };
        /** RegisterServerRequest */
        RegisterServerRequest: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Endpoint */
            endpoint: string;
            /** @default 20 */
            min_trust_tier: components["schemas"]["TrustTier"];
            /**
             * Requires Approval
             * @default true
             */
            requires_approval: boolean;
        };
        /** RegisterSourceRequest */
        RegisterSourceRequest: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "s3" | "minio" | "local_fs" | "http";
            /** Bucket */
            bucket?: string | null;
            /** Prefix */
            prefix?: string | null;
            /** Root */
            root?: string | null;
            /** Urls */
            urls?: string[] | null;
        };
        /** RejectionResponse */
        RejectionResponse: {
            /** Key */
            key: string;
            /** Section */
            section: string;
            /** Source Kind */
            source_kind: string;
            /** Source Ref */
            source_ref: string;
            /** Reason */
            reason: string;
            /** Tokens */
            tokens: number;
            /** Utility */
            utility: number;
            /** Detail */
            detail: string | null;
        };
        /** RenameSessionRequest */
        RenameSessionRequest: {
            /** Title */
            title?: string | null;
            /** Folder Id */
            folder_id?: string | null;
        };
        /** RevokeRequest */
        RevokeRequest: {
            /**
             * Refresh Token
             * @description Omit when the refresh cookie is present.
             */
            refresh_token?: string | null;
        };
        /** SaveCredentialRequest */
        SaveCredentialRequest: {
            /**
             * Scheme
             * @enum {string}
             */
            scheme: "none" | "bearer" | "api_key";
            /**
             * Secret
             * Format: password
             * @default
             */
            secret: string;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Content */
            content: string;
        };
        /** ServerResponse */
        ServerResponse: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Endpoint */
            endpoint: string;
            /** Min Trust Tier */
            min_trust_tier: number;
            /** Requires Approval */
            requires_approval: boolean;
            /** Last Discovered At */
            last_discovered_at: string | null;
            /** Health Status */
            health_status: string | null;
            /** Credential Configured */
            credential_configured: boolean;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Created At */
            created_at: string;
        };
        /**
         * TokenRequest
         * @description `grant_type=refresh_token`.
         *
         *     `refresh_token` is optional because a browser sends it as an `httpOnly`
         *     cookie and has no way to read it back into a body. A non-browser client that
         *     holds its own token sends it here instead.
         */
        TokenRequest: {
            /**
             * Grant Type
             * @description Only `refresh_token` is supported here. The password and api_key grants are M3.5; OIDC logins go through `/auth/oidc/authorize`.
             * @constant
             */
            grant_type: "refresh_token";
            /**
             * Refresh Token
             * @description Omit when the refresh cookie is present, which is the browser case.
             */
            refresh_token?: string | null;
        };
        /**
         * TokenResponse
         * @description A minted access token, and where to send it.
         *
         *     **There is no `refresh_token` field, and that is the design.** The refresh
         *     token is set as an `httpOnly` cookie on this same response; returning it in
         *     the body would invite a browser client to keep it in `localStorage`, which
         *     any cross-site scripting bug can read. A response body is also the thing most
         *     likely to end up in a log, a proxy cache, or a pasted bug report.
         *
         *     `APIContract.md` §2 used to show a `refresh_token` field. It is corrected in
         *     the same commit as this class rather than left to disagree with the code.
         *
         *     No `scope` field either: an access token carries identity and no
         *     authorization, so there is no scope to report. Effective permissions come
         *     from `GET /auth/me` (M3.6) against the live database, which is what makes a
         *     revoked role take effect on the next request rather than in fifteen minutes.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description Bearer token, 15 minutes, identity claims only
             */
            access_token: string;
            /**
             * Token Type
             * @default Bearer
             * @constant
             */
            token_type: "Bearer";
            /**
             * Expires In
             * @description Access token lifetime in seconds
             */
            expires_in: number;
            /**
             * Org Slug
             * @description Tenant this session belongs to
             */
            org_slug: string;
        };
        /** ToolResponse */
        ToolResponse: {
            /** Id */
            id: string;
            /** Server Id */
            server_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /** Requires Approval */
            requires_approval: boolean;
            /** Is Mutating */
            is_mutating: boolean;
        };
        /**
         * TrustTier
         * @description How far a piece of context is allowed to influence the model.
         *
         *     Ordering is load-bearing: the context compiler fences lower tiers so that
         *     retrieved document text can never be read as an instruction. Untrusted
         *     content is quoted, never obeyed.
         * @enum {integer}
         */
        TrustTier: 40 | 30 | 20 | 10;
        /** UpdateFolderRequest */
        UpdateFolderRequest: {
            /** Name */
            name?: string | null;
            /** Position */
            position?: number | null;
        };
        /** UpsertBookmarkRequest */
        UpsertBookmarkRequest: {
            /** Note */
            note?: string | null;
        };
        /** UpsertFeedbackRequest */
        UpsertFeedbackRequest: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
            /** Comment */
            comment?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    oidc_authorize_api_v1_auth_oidc_authorize_get: {
        parameters: {
            query: {
                /** @description Org slug to log into */
                org: string;
                /** @description Provider slug; the org default if omitted */
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oidc_callback_api_v1_auth_oidc_callback_get: {
        parameters: {
            query: {
                state: string;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    issue_token_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_token_api_v1_auth_token_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_api_v1_chat_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_chat_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_folders_api_v1_chat_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderListResponse"];
                };
            };
        };
    };
    create_folder_api_v1_chat_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_v1_chat_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_folder_api_v1_chat_folders__folder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_bookmark_api_v1_chat_messages__message_id__bookmark_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertBookmarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_bookmark_api_v1_chat_messages__message_id__bookmark_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookmarks_api_v1_chat_bookmarks_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_feedback_api_v1_chat_messages__message_id__feedback_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_feedback_api_v1_chat_messages__message_id__feedback_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_knowledge_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
        };
    };
    upload_document_api_v1_knowledge_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_knowledge_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_knowledge_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_knowledge_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
        };
    };
    register_source_api_v1_connectors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_connectors_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_connectors_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_connectors__slug__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_item_api_v1_connectors__slug__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_servers_api_v1_tools_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"][];
                };
            };
        };
    };
    register_server_api_v1_tools_servers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterServerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_credential_api_v1_tools_servers__server_id__credential_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_tools_api_v1_tools_servers__server_id__discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolResponse"][];
                };
            };
        };
    };
    grant_tool_to_self_api_v1_tools__tool_id__grants_self_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantSelfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invocations_api_v1_tools_invocations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvocationResponse"][];
                };
            };
        };
    };
    propose_invocation_api_v1_tools_invocations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeInvocationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_invocation_api_v1_tools_invocations__invocation_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deny_invocation_api_v1_tools_invocations__invocation_id__deny_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memory_history_api_v1_memories_get: {
        parameters: {
            query?: {
                subject_ref?: string | null;
                as_of?: string | null;
                believed_at?: string | null;
                include_retracted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory_api_v1_memories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supersede_memory_api_v1_memories__memory_id__supersede_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retract_memory_api_v1_memories__memory_id__retract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_bundle_api_v1_context_messages__message_id__bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextBundleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
