/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — touches no dependency */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — checks dependencies */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin OIDC authorization code + PKCE
         * @description 307 the browser to the IdP's **public** issuer.
         *
         *     `RedirectResponse` defaults to 307 and the method is GET either way, so no
         *     body is at stake.
         *
         *     A denial here — unknown org, disabled provider, an org whose default is a
         *     password provider — sends the browser back to the sign-in screen rather than
         *     rendering a JSON 401 at it. See the module docstring: the answer is one
         *     constant either way, and the caller is a browser.
         */
        get: operations["oidc_authorize_api_v1_auth_oidc_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OIDC callback: open a session and return the browser to the app
         * @description Verify `state`, exchange `code` server-side, validate the token, open a session.
         *
         *     M3.3 ended here with a `SubjectResponse` — proof that a login *happened*,
         *     with no way to stay logged in. M3.4 made it a token pair in a JSON body,
         *     which is right for a test client and wrong for the only caller it has: this
         *     endpoint is reached by a top-level navigation from Keycloak, so a JSON body
         *     is a page of text rendered at a person who expected an application.
         *
         *     It therefore sets the refresh cookie and redirects, **carrying no token in
         *     the URL**. The page it lands on exchanges the cookie for an access token.
         *
         *     `error` is what the IdP sends when the user cancels or is refused. It is a
         *     denial like any other and is never echoed back: the IdP's error strings are
         *     diagnostic and can name internal configuration.
         */
        get: operations["oidc_callback_api_v1_auth_oidc_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current principal, resolved against the live database
         * @description The first route in the system that is **not** in the public allow-list.
         *
         *     It declares no guard of its own — `require_caller` only *reads* the identity
         *     the application-level dependency already resolved — which is the whole point:
         *     being authenticated is what a route gets for doing nothing.
         */
        get: operations["read_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new access token
         * @description Rotate the refresh token and mint a fresh access token.
         *
         *     **Every call rotates.** The token that came in is retired and a new one goes
         *     out on the cookie; presenting the retired one again revokes the entire chain,
         *     because at that point two parties hold copies of one credential and nothing
         *     here can tell which one is the thief.
         *
         *     The practical consequence for a client is that *concurrent* refreshes are
         *     indistinguishable from theft and must be collapsed into one in-flight call.
         *     That is the frontend half of M3.4 and it is written down in TRACKER §5.
         */
        post: operations["issue_token_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token:revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token and its whole rotation chain
         * @description Sign out. **Always 204**, whatever was presented.
         *
         *     RFC 7009 §2.2 asks for the same, and the reason is worth stating: an endpoint
         *     that answers 401 for an unknown token and 204 for a known one is a free oracle
         *     for testing stolen credentials — and the caller is unauthenticated, because
         *     presenting the token *is* the authentication. So unknown, expired, malformed
         *     and absent all get one answer, and the cookie is cleared either way rather
         *     than leaving a client holding a credential it believes it revoked.
         */
        post: operations["revoke_token_api_v1_auth_token_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_chat_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_v1_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Rename Session */
        patch: operations["rename_session_api_v1_chat_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_chat_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_knowledge_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_knowledge_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_knowledge_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_knowledge_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_connectors_get"];
        put?: never;
        /** Register Source */
        post: operations["register_source_api_v1_connectors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_connectors_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_connectors_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{slug}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_connectors__slug__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{slug}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Item
         * @description Enqueue a `queued` `ingest_job` for one item the source currently
         *     lists — the second producer `entrypoints/worker/main.py`'s docstring
         *     already anticipated. Refuses a `uri` the source does not currently list,
         *     same discipline `mnemosctl connector ingest` enforces, so this can never
         *     become an arbitrary-fetch primitive for a slug the caller's org owns.
         */
        post: operations["ingest_item_api_v1_connectors__slug__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_knowledge_documents_post */
        Body_upload_document_api_v1_knowledge_documents_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            /** Id */
            id: string;
            /** Ordinal */
            ordinal: number;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Flow */
            flow: string | null;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Latency Ms */
            latency_ms: number | null;
            /** Model */
            model: string | null;
            /** Finish Reason */
            finish_reason: string | null;
            /** Created At */
            created_at: string;
        };
        /** ChatSessionDetailResponse */
        ChatSessionDetailResponse: {
            session: components["schemas"]["ChatSessionResponse"];
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
            /** Citations */
            citations: components["schemas"]["CitationResponse"][];
        };
        /** ChatSessionListResponse */
        ChatSessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["ChatSessionResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ChatSessionResponse */
        ChatSessionResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Is Archived */
            is_archived: boolean;
            /** Last Message At */
            last_message_at: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** CitationResponse */
        CitationResponse: {
            /** Id */
            id: string;
            /** Message Id */
            message_id: string;
            /** Marker */
            marker: number;
            /** Document Id */
            document_id: string | null;
            /** Chunk Id */
            chunk_id: string | null;
            /** Quoted Text */
            quoted_text: string;
            /** Start Char */
            start_char: number | null;
            /** End Char */
            end_char: number | null;
            /** Page Number */
            page_number: number | null;
            /** Score */
            score: number | null;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Title */
            title?: string | null;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Media Type */
            media_type: string;
            /** Byte Size */
            byte_size: number;
            /** Status */
            status: string;
            /** Superseded By */
            superseded_by: string | null;
            /** Chunk Count */
            chunk_count: number;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestJobEventResponse */
        IngestJobEventResponse: {
            /** Id */
            id: string;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string;
            /** Owner Id */
            owner_id: string | null;
            /** Detail */
            detail: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** IngestJobResponse */
        IngestJobResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Payload */
            payload: {
                [key: string]: string;
            };
            /** Document Id */
            document_id: string | null;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Done Units */
            done_units: number;
            /** Total Units */
            total_units: number;
            /** Owner Id */
            owner_id: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Events */
            events: components["schemas"]["IngestJobEventResponse"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /** Uri */
            uri: string;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Uri */
            uri: string;
        };
        /** ItemResponse */
        ItemResponse: {
            /** Uri */
            uri: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Content Type */
            content_type: string;
            /** Modified At */
            modified_at: string | null;
        };
        /**
         * MeResponse
         * @description Who the bearer of this access token is, resolved against the live database.
         *
         *     **Every field here was read on this request, not carried in the token.** The
         *     token names a user, an org and a session and says nothing about authority
         *     (`domain/token.py`), so `permissions` and `tags` are the repository's answer
         *     a moment ago rather than the IdP's answer at login. That is what makes a
         *     revoked role take effect on the next call instead of in fifteen minutes, and
         *     it is observable here: mint a token, change a binding, call this again.
         *
         *     `permissions` is reported, not enforced. The permission matrix — requiring a
         *     concrete `resource:action` per route — is a later milestone; listing the
         *     grants is how the shell knows what to offer, and hiding a control is a
         *     courtesy rather than the control itself.
         */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Org Id */
            org_id: string;
            /** Org Slug */
            org_slug: string;
            /** Session Id */
            session_id: string;
            /**
             * Permissions
             * @description Effective `resource:action` grants, live
             */
            permissions: string[];
            /**
             * Tags
             * @description Tag slugs this principal can reach (constraint C4)
             */
            tags: string[];
        };
        /** RegisterSourceRequest */
        RegisterSourceRequest: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "s3" | "minio" | "local_fs" | "http";
            /** Bucket */
            bucket?: string | null;
            /** Prefix */
            prefix?: string | null;
            /** Root */
            root?: string | null;
            /** Urls */
            urls?: string[] | null;
        };
        /** RenameSessionRequest */
        RenameSessionRequest: {
            /** Title */
            title: string;
        };
        /** RevokeRequest */
        RevokeRequest: {
            /**
             * Refresh Token
             * @description Omit when the refresh cookie is present.
             */
            refresh_token?: string | null;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Content */
            content: string;
            /**
             * Use Documents
             * @default false
             */
            use_documents: boolean;
            /**
             * Use Datasource
             * @default false
             */
            use_datasource: boolean;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Created At */
            created_at: string;
        };
        /**
         * TokenRequest
         * @description `grant_type=refresh_token`.
         *
         *     `refresh_token` is optional because a browser sends it as an `httpOnly`
         *     cookie and has no way to read it back into a body. A non-browser client that
         *     holds its own token sends it here instead.
         */
        TokenRequest: {
            /**
             * Grant Type
             * @description Only `refresh_token` is supported here. The password and api_key grants are M3.5; OIDC logins go through `/auth/oidc/authorize`.
             * @constant
             */
            grant_type: "refresh_token";
            /**
             * Refresh Token
             * @description Omit when the refresh cookie is present, which is the browser case.
             */
            refresh_token?: string | null;
        };
        /**
         * TokenResponse
         * @description A minted access token, and where to send it.
         *
         *     **There is no `refresh_token` field, and that is the design.** The refresh
         *     token is set as an `httpOnly` cookie on this same response; returning it in
         *     the body would invite a browser client to keep it in `localStorage`, which
         *     any cross-site scripting bug can read. A response body is also the thing most
         *     likely to end up in a log, a proxy cache, or a pasted bug report.
         *
         *     `APIContract.md` §2 used to show a `refresh_token` field. It is corrected in
         *     the same commit as this class rather than left to disagree with the code.
         *
         *     No `scope` field either: an access token carries identity and no
         *     authorization, so there is no scope to report. Effective permissions come
         *     from `GET /auth/me` (M3.6) against the live database, which is what makes a
         *     revoked role take effect on the next request rather than in fifteen minutes.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description Bearer token, 15 minutes, identity claims only
             */
            access_token: string;
            /**
             * Token Type
             * @default Bearer
             * @constant
             */
            token_type: "Bearer";
            /**
             * Expires In
             * @description Access token lifetime in seconds
             */
            expires_in: number;
            /**
             * Org Slug
             * @description Tenant this session belongs to
             */
            org_slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    oidc_authorize_api_v1_auth_oidc_authorize_get: {
        parameters: {
            query: {
                /** @description Org slug to log into */
                org: string;
                /** @description Provider slug; the org default if omitted */
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oidc_callback_api_v1_auth_oidc_callback_get: {
        parameters: {
            query: {
                state: string;
                code?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    issue_token_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_token_api_v1_auth_token_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_api_v1_chat_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_chat_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_knowledge_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
        };
    };
    upload_document_api_v1_knowledge_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_knowledge_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_knowledge_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_knowledge_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
        };
    };
    register_source_api_v1_connectors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_connectors_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_connectors_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_connectors__slug__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_item_api_v1_connectors__slug__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
