"""initial schema — all 41 tables across identity, memory, knowledge, chat,
context, datasources, tools, prompts and observability.

Autogenerated from `mnemos.platform.models` and kept in sync by `alembic check`,
which is wired into `make check-migrations`. Everything a model cannot express —
the bitemporal exclusion constraint, the monthly partitions, row-level security —
lands in the revisions that follow, so each of those can be read and reverted on
its own.

Revision ID: 0001
Revises:
Created: 2026-07-26
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "org",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org")),
        sa.UniqueConstraint("slug", name=op.f("uq_org_slug")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_kind", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_audit_log_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_actor_id_occurred_at", "audit_log", ["actor_id", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_index(
        "ix_audit_log_org_id_action_occurred_at",
        "audit_log",
        ["org_id", "action", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_org_id_occurred_at", "audit_log", ["org_id", "occurred_at"], unique=False
    )
    op.create_table(
        "collection",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_collection_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection")),
        sa.UniqueConstraint("org_id", "slug", name="uq_collection_org_id_slug"),
    )
    op.create_index(op.f("ix_collection_org_id"), "collection", ["org_id"], unique=False)
    op.create_table(
        "context_plan",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("query_sha256", sa.String(length=64), nullable=False),
        sa.Column("total_budget", sa.Integer(), nullable=False),
        sa.Column(
            "section_budgets",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "operators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("deadline_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_context_plan_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_plan")),
    )
    op.create_index(op.f("ix_context_plan_org_id"), "context_plan", ["org_id"], unique=False)
    op.create_index(
        "ix_context_plan_org_id_created_at", "context_plan", ["org_id", "created_at"], unique=False
    )
    op.create_table(
        "identity_provider",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("issuer_public", sa.Text(), nullable=True),
        sa.Column("issuer_internal", sa.Text(), nullable=True),
        sa.Column("client_id", sa.Text(), nullable=True),
        sa.Column("client_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('internal', 'oidc', 'api_key')", name=op.f("ck_identity_provider_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_identity_provider_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_provider")),
        sa.UniqueConstraint("org_id", "slug", name="uq_identity_provider_org_id_slug"),
    )
    op.create_index(
        op.f("ix_identity_provider_org_id"), "identity_provider", ["org_id"], unique=False
    )
    op.create_table(
        "inference_call",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("time_to_first_token_ms", sa.Integer(), nullable=True),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "prompt_tokens >= 0 AND completion_tokens >= 0",
            name=op.f("ck_inference_call_tokens_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_inference_call_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "occurred_at", name=op.f("pk_inference_call")),
        postgresql_partition_by="RANGE (occurred_at)",
    )
    op.create_index(op.f("ix_inference_call_org_id"), "inference_call", ["org_id"], unique=False)
    op.create_index(
        "ix_inference_call_org_id_model_occurred_at",
        "inference_call",
        ["org_id", "model", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_inference_call_org_id_occurred_at",
        "inference_call",
        ["org_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "mcp_server",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transport", sa.String(length=16), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column(
            "command",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "min_trust_tier", sa.SmallInteger(), server_default=sa.text("20"), nullable=False
        ),
        sa.Column(
            "requires_approval", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "acl_tag_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("last_discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_status", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transport IN ('stdio', 'http', 'sse')", name=op.f("ck_mcp_server_transport_valid")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_mcp_server_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_server")),
        sa.UniqueConstraint("org_id", "slug", name="uq_mcp_server_org_id_slug"),
    )
    op.create_index(op.f("ix_mcp_server_org_id"), "mcp_server", ["org_id"], unique=False)
    op.create_table(
        "prompt",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('system', 'rag', 'nl2sql', 'router', 'agent', 'summarize', 'memory')",
            name=op.f("ck_prompt_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_prompt_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt")),
        sa.UniqueConstraint("org_id", "slug", name="uq_prompt_org_id_slug"),
    )
    op.create_index(op.f("ix_prompt_org_id"), "prompt", ["org_id"], unique=False)
    op.create_table(
        "role",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_role_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("org_id", "slug", name="uq_role_org_id_slug"),
    )
    op.create_index(op.f("ix_role_org_id"), "role", ["org_id"], unique=False)
    op.create_table(
        "sql_datasource",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "dialect", sa.String(length=32), server_default=sa.text("'postgres'"), nullable=False
        ),
        sa.Column("dsn_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("read_only_role", sa.Text(), nullable=False),
        sa.Column(
            "allowed_schemas",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "allowed_tables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "acl_tag_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "statement_timeout_ms", sa.Integer(), server_default=sa.text("15000"), nullable=False
        ),
        sa.Column("max_rows", sa.Integer(), server_default=sa.text("5000"), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("introspected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dialect IN ('postgres')", name=op.f("ck_sql_datasource_dialect_supported")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_sql_datasource_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sql_datasource")),
        sa.UniqueConstraint("org_id", "slug", name="uq_sql_datasource_org_id_slug"),
    )
    op.create_index(op.f("ix_sql_datasource_org_id"), "sql_datasource", ["org_id"], unique=False)
    op.create_table(
        "subject",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_subject_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subject")),
        sa.UniqueConstraint(
            "org_id", "kind", "external_ref", name="uq_subject_org_id_kind_external_ref"
        ),
    )
    op.create_index(op.f("ix_subject_org_id"), "subject", ["org_id"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_tag_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
        sa.UniqueConstraint("org_id", "slug", name="uq_tag_org_id_slug"),
    )
    op.create_index(op.f("ix_tag_org_id"), "tag", ["org_id"], unique=False)
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("external_subject", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_app_user_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["identity_provider.id"],
            name=op.f("fk_app_user_provider_id_identity_provider"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("org_id", "email", name="uq_app_user_org_id_email"),
    )
    op.create_index(op.f("ix_app_user_org_id"), "app_user", ["org_id"], unique=False)
    op.create_index(
        "ix_app_user_org_id_external_subject",
        "app_user",
        ["org_id", "external_subject"],
        unique=False,
    )
    op.create_table(
        "glossary_term",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("datasource_id", sa.UUID(), nullable=True),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("sql_expression", sa.Text(), nullable=True),
        sa.Column(
            "synonyms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["sql_datasource.id"],
            name=op.f("fk_glossary_term_datasource_id_sql_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_glossary_term_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_term")),
        sa.UniqueConstraint(
            "org_id", "datasource_id", "term", name="uq_glossary_term_org_id_datasource_id_term"
        ),
    )
    op.create_index(op.f("ix_glossary_term_org_id"), "glossary_term", ["org_id"], unique=False)
    op.create_table(
        "mcp_tool",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "input_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "requires_approval", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("is_mutating", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_mcp_tool_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mcp_server.id"],
            name=op.f("fk_mcp_tool_server_id_mcp_server"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_tool")),
        sa.UniqueConstraint("server_id", "name", name="uq_mcp_tool_server_id_name"),
    )
    op.create_index(op.f("ix_mcp_tool_org_id"), "mcp_tool", ["org_id"], unique=False)
    op.create_index(
        "ix_mcp_tool_org_id_server_id", "mcp_tool", ["org_id", "server_id"], unique=False
    )
    op.create_table(
        "sql_schema_object",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("datasource_id", sa.UUID(), nullable=False),
        sa.Column("schema_name", sa.Text(), nullable=False),
        sa.Column("table_name", sa.Text(), nullable=False),
        sa.Column("column_name", sa.Text(), nullable=True),
        sa.Column("data_type", sa.Text(), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "sample_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("row_estimate", sa.Integer(), nullable=True),
        sa.Column(
            "introspected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["sql_datasource.id"],
            name=op.f("fk_sql_schema_object_datasource_id_sql_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_sql_schema_object_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sql_schema_object")),
        sa.UniqueConstraint(
            "datasource_id",
            "schema_name",
            "table_name",
            "column_name",
            name="uq_sql_schema_object_qualified_column",
        ),
    )
    op.create_index(
        op.f("ix_sql_schema_object_org_id"), "sql_schema_object", ["org_id"], unique=False
    )
    op.create_index(
        "ix_sql_schema_object_org_id_datasource_id",
        "sql_schema_object",
        ["org_id", "datasource_id"],
        unique=False,
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_api_key_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_api_key_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("key_hash", name="uq_api_key_key_hash"),
    )
    op.create_index(op.f("ix_api_key_org_id"), "api_key", ["org_id"], unique=False)
    op.create_index(op.f("ix_api_key_user_id"), "api_key", ["user_id"], unique=False)
    op.create_table(
        "document",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("lineage_key", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "acl_tag_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("trust_tier", sa.SmallInteger(), server_default=sa.text("10"), nullable=False),
        sa.Column(
            "doc_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind IN ('minio', 's3', 'local_fs', 'http')",
            name=op.f("ck_document_source_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'ready', 'failed', 'superseded', 'deleted')",
            name=op.f("ck_document_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_document_collection_id_collection"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_document_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["document.id"],
            name=op.f("fk_document_superseded_by_document"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["app_user.id"],
            name=op.f("fk_document_uploaded_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
        sa.UniqueConstraint("org_id", "content_sha256", name="uq_document_org_id_content_sha256"),
    )
    op.create_index(op.f("ix_document_org_id"), "document", ["org_id"], unique=False)
    op.create_index(
        "ix_document_org_id_collection_id_status",
        "document",
        ["org_id", "collection_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_document_org_id_lineage_key", "document", ["org_id", "lineage_key"], unique=False
    )
    op.create_table(
        "folder",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_folder_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_folder_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folder")),
        sa.UniqueConstraint("org_id", "user_id", "name", name="uq_folder_org_id_user_id_name"),
    )
    op.create_index(op.f("ix_folder_org_id"), "folder", ["org_id"], unique=False)
    op.create_index(op.f("ix_folder_user_id"), "folder", ["user_id"], unique=False)
    op.create_table(
        "mcp_credential",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("secret_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_mcp_credential_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mcp_server.id"],
            name=op.f("fk_mcp_credential_server_id_mcp_server"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_mcp_credential_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_credential")),
        sa.UniqueConstraint("server_id", "user_id", name="uq_mcp_credential_server_id_user_id"),
    )
    op.create_index(op.f("ix_mcp_credential_org_id"), "mcp_credential", ["org_id"], unique=False)
    op.create_index(op.f("ix_mcp_credential_user_id"), "mcp_credential", ["user_id"], unique=False)
    op.create_table(
        "mcp_grant",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column("auto_approve", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["app_user.id"],
            name=op.f("fk_mcp_grant_granted_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_mcp_grant_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["mcp_tool.id"],
            name=op.f("fk_mcp_grant_tool_id_mcp_tool"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_mcp_grant_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_grant")),
        sa.UniqueConstraint("tool_id", "user_id", name="uq_mcp_grant_tool_id_user_id"),
    )
    op.create_index(op.f("ix_mcp_grant_org_id"), "mcp_grant", ["org_id"], unique=False)
    op.create_index(op.f("ix_mcp_grant_user_id"), "mcp_grant", ["user_id"], unique=False)
    op.create_table(
        "memory",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("predicate", sa.Text(), nullable=False),
        sa.Column("object_text", sa.Text(), nullable=False),
        sa.Column(
            "object_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "scope",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("scope_hash", sa.String(length=64), nullable=False),
        sa.Column("valid_range", postgresql.TSTZRANGE(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False),
        sa.Column("trust_tier", sa.SmallInteger(), server_default=sa.text("20"), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=True),
        sa.Column("source_message_id", sa.UUID(), nullable=True),
        sa.Column(
            "acl_tag_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('fact', 'preference', 'decision', 'observation')",
            name=op.f("ck_memory_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'superseded', 'retracted')", name=op.f("ck_memory_status_valid")
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name=op.f("ck_memory_confidence_unit_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_memory_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_memory_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
            name=op.f("fk_memory_subject_id_subject"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory")),
    )
    op.create_index(op.f("ix_memory_org_id"), "memory", ["org_id"], unique=False)
    op.create_index(
        "ix_memory_org_id_status_recorded_at",
        "memory",
        ["org_id", "status", "recorded_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_org_id_subject_id_predicate",
        "memory",
        ["org_id", "subject_id", "predicate"],
        unique=False,
        postgresql_where=sa.text("retracted_at IS NULL"),
    )
    op.create_index(
        "ix_memory_valid_range", "memory", ["valid_range"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "prompt_version",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_prompt_version_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_prompt_version_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompt.id"],
            name=op.f("fk_prompt_version_prompt_id_prompt"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_version")),
        sa.UniqueConstraint("prompt_id", "version", name="uq_prompt_version_prompt_id_version"),
    )
    op.create_index(op.f("ix_prompt_version_org_id"), "prompt_version", ["org_id"], unique=False)
    op.create_index(
        "uq_prompt_version_one_active",
        "prompt_version",
        ["prompt_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "role_binding",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.Text(), server_default=sa.text("'*'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_role_binding_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_role_binding_role_id_role"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_role_binding_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_binding")),
        sa.UniqueConstraint(
            "user_id", "role_id", "scope", name="uq_role_binding_user_id_role_id_scope"
        ),
    )
    op.create_index(op.f("ix_role_binding_org_id"), "role_binding", ["org_id"], unique=False)
    op.create_index(op.f("ix_role_binding_user_id"), "role_binding", ["user_id"], unique=False)
    op.create_table(
        "session",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("rotated_to", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_session_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rotated_to"],
            ["session.id"],
            name=op.f("fk_session_rotated_to_session"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_session_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("refresh_token_hash", name="uq_session_refresh_token_hash"),
    )
    op.create_index(op.f("ix_session_org_id"), "session", ["org_id"], unique=False)
    op.create_index(
        "ix_session_user_id_expires_at", "session", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "user_tag",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_user_tag_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name=op.f("fk_user_tag_tag_id_tag"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_tag_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_tag")),
        sa.UniqueConstraint("user_id", "tag_id", name="uq_user_tag_user_id_tag_id"),
    )
    op.create_index(op.f("ix_user_tag_org_id"), "user_tag", ["org_id"], unique=False)
    op.create_index(op.f("ix_user_tag_tag_id"), "user_tag", ["tag_id"], unique=False)
    op.create_index(op.f("ix_user_tag_user_id"), "user_tag", ["user_id"], unique=False)
    op.create_table(
        "chat_session",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), server_default=sa.text("'New chat'"), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("token_budget", sa.Integer(), server_default=sa.text("3000"), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folder.id"],
            name=op.f("fk_chat_session_folder_id_folder"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_chat_session_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_chat_session_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_session")),
    )
    op.create_index(op.f("ix_chat_session_org_id"), "chat_session", ["org_id"], unique=False)
    op.create_index(
        "ix_chat_session_org_id_user_id_last_message_at",
        "chat_session",
        ["org_id", "user_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "chunk",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=False),
        sa.Column("end_char", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column(
            "heading_path",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_chunk_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_chunk_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunk_document_id_ordinal"),
    )
    op.create_index(op.f("ix_chunk_org_id"), "chunk", ["org_id"], unique=False)
    op.create_index("ix_chunk_org_id_document_id", "chunk", ["org_id", "document_id"], unique=False)
    op.create_index(
        "ix_chunk_text_trgm",
        "chunk",
        ["text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    op.create_table(
        "ingest_job",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'queued'"), nullable=False
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Text(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("total_units", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("done_units", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled', 'stuck')",
            name=op.f("ck_ingest_job_status_valid"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_ingest_job_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_ingest_job_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_ingest_job_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_job")),
        sa.UniqueConstraint("idempotency_key", name="uq_ingest_job_idempotency_key"),
    )
    op.create_index(op.f("ix_ingest_job_org_id"), "ingest_job", ["org_id"], unique=False)
    op.create_index(
        "ix_ingest_job_org_id_created_at", "ingest_job", ["org_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_ingest_job_status_heartbeat_at", "ingest_job", ["status", "heartbeat_at"], unique=False
    )
    op.create_table(
        "memory_edge",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("src_id", sa.UUID(), nullable=False),
        sa.Column("dst_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('supersedes', 'contradicts', 'supports', 'derived_from')",
            name=op.f("ck_memory_edge_kind_valid"),
        ),
        sa.CheckConstraint("src_id <> dst_id", name=op.f("ck_memory_edge_no_self_edge")),
        sa.ForeignKeyConstraint(
            ["dst_id"], ["memory.id"], name=op.f("fk_memory_edge_dst_id_memory"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_memory_edge_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["src_id"], ["memory.id"], name=op.f("fk_memory_edge_src_id_memory"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_edge")),
        sa.UniqueConstraint("src_id", "dst_id", "kind", name="uq_memory_edge_src_id_dst_id_kind"),
    )
    op.create_index("ix_memory_edge_dst_id_kind", "memory_edge", ["dst_id", "kind"], unique=False)
    op.create_index(op.f("ix_memory_edge_org_id"), "memory_edge", ["org_id"], unique=False)
    op.create_index(op.f("ix_memory_edge_src_id"), "memory_edge", ["src_id"], unique=False)
    op.create_table(
        "memory_embedding",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=384), nullable=False),
        sa.Column("is_live", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "acl_tag_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memory.id"],
            name=op.f("fk_memory_embedding_memory_id_memory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_memory_embedding_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_embedding")),
        sa.UniqueConstraint("memory_id", "model", name="uq_memory_embedding_memory_id_model"),
    )
    op.create_index(
        op.f("ix_memory_embedding_org_id"), "memory_embedding", ["org_id"], unique=False
    )
    op.create_index(
        "ix_memory_embedding_org_id_is_live",
        "memory_embedding",
        ["org_id", "is_live"],
        unique=False,
        postgresql_where=sa.text("is_live"),
    )
    op.create_index(
        "ix_memory_embedding_vector_hnsw",
        "memory_embedding",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
    )
    op.create_table(
        "chunk_embedding",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=384), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "acl_tag_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("trust_tier", sa.SmallInteger(), server_default=sa.text("10"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunk.id"],
            name=op.f("fk_chunk_embedding_chunk_id_chunk"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_chunk_embedding_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_chunk_embedding_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk_embedding")),
        sa.UniqueConstraint("chunk_id", "model", name="uq_chunk_embedding_chunk_id_model"),
    )
    op.create_index(op.f("ix_chunk_embedding_org_id"), "chunk_embedding", ["org_id"], unique=False)
    op.create_index(
        "ix_chunk_embedding_org_id_is_current",
        "chunk_embedding",
        ["org_id", "is_current"],
        unique=False,
        postgresql_where=sa.text("is_current"),
    )
    op.create_index(
        "ix_chunk_embedding_vector_hnsw",
        "chunk_embedding",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
    )
    op.create_table(
        "context_bundle",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("flow", sa.String(length=32), nullable=False),
        sa.Column("token_budget", sa.Integer(), nullable=False),
        sa.Column("tokens_consumed", sa.Integer(), nullable=False),
        sa.Column(
            "budget_report",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "rejections",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("compiled_prompt", sa.Text(), nullable=False),
        sa.Column("embedder", sa.String(length=128), nullable=False),
        sa.Column("tokenizer", sa.String(length=64), nullable=False),
        sa.Column("compile_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tokens_consumed <= token_budget", name=op.f("ck_context_bundle_budget_not_exceeded")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_context_bundle_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["context_plan.id"],
            name=op.f("fk_context_bundle_plan_id_context_plan"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.id"],
            name=op.f("fk_context_bundle_session_id_chat_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_bundle")),
        sa.UniqueConstraint("org_id", "digest", name="uq_context_bundle_org_id_digest"),
    )
    op.create_index(op.f("ix_context_bundle_org_id"), "context_bundle", ["org_id"], unique=False)
    op.create_index(
        "ix_context_bundle_org_id_created_at",
        "context_bundle",
        ["org_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ingest_job_event",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingest_job.id"],
            name=op.f("fk_ingest_job_event_job_id_ingest_job"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_ingest_job_event_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_job_event")),
    )
    op.create_index(
        "ix_ingest_job_event_job_id_occurred_at",
        "ingest_job_event",
        ["job_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_job_event_org_id"), "ingest_job_event", ["org_id"], unique=False
    )
    op.create_table(
        "bundle_item",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("bundle_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("operator", sa.String(length=32), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("memory_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("text_snapshot", sa.Text(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("rrf_score", sa.Float(), nullable=False),
        sa.Column("utility", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("trust_tier", sa.SmallInteger(), nullable=False),
        sa.Column("acl_rule_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operator IN ('vector', 'lexical', 'memory', 'sql', 'tool', 'history')",
            name=op.f("ck_bundle_item_operator_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["acl_rule_id"],
            ["tag.id"],
            name=op.f("fk_bundle_item_acl_rule_id_tag"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["context_bundle.id"],
            name=op.f("fk_bundle_item_bundle_id_context_bundle"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunk.id"],
            name=op.f("fk_bundle_item_chunk_id_chunk"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_bundle_item_document_id_document"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memory.id"],
            name=op.f("fk_bundle_item_memory_id_memory"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_bundle_item_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bundle_item")),
        sa.UniqueConstraint("bundle_id", "position", name="uq_bundle_item_bundle_id_position"),
    )
    op.create_index(op.f("ix_bundle_item_org_id"), "bundle_item", ["org_id"], unique=False)
    op.create_index(
        "ix_bundle_item_org_id_bundle_id_position",
        "bundle_item",
        ["org_id", "bundle_id", "position"],
        unique=False,
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("flow", sa.String(length=32), nullable=True),
        sa.Column("router_confidence", sa.Float(), nullable=True),
        sa.Column("router_rationale", sa.Text(), nullable=True),
        sa.Column("bundle_id", sa.UUID(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "msg_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('system', 'user', 'assistant', 'tool')",
            name=op.f("ck_chat_message_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["context_bundle.id"],
            name=op.f("fk_chat_message_bundle_id_context_bundle"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_chat_message_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.id"],
            name=op.f("fk_chat_message_session_id_chat_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_message")),
        sa.UniqueConstraint("session_id", "ordinal", name="uq_chat_message_session_id_ordinal"),
    )
    op.create_index(op.f("ix_chat_message_org_id"), "chat_message", ["org_id"], unique=False)
    op.create_index(
        "ix_chat_message_org_id_session_id_ordinal",
        "chat_message",
        ["org_id", "session_id", "ordinal"],
        unique=False,
    )
    op.create_table(
        "bookmark",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_message.id"],
            name=op.f("fk_bookmark_message_id_chat_message"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_bookmark_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_bookmark_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmark")),
        sa.UniqueConstraint("user_id", "message_id", name="uq_bookmark_user_id_message_id"),
    )
    op.create_index(op.f("ix_bookmark_org_id"), "bookmark", ["org_id"], unique=False)
    op.create_index(op.f("ix_bookmark_user_id"), "bookmark", ["user_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating IN ('up', 'down')", name=op.f("ck_feedback_rating_valid")),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_message.id"],
            name=op.f("fk_feedback_message_id_chat_message"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_feedback_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_feedback_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("user_id", "message_id", name="uq_feedback_user_id_message_id"),
    )
    op.create_index(op.f("ix_feedback_message_id"), "feedback", ["message_id"], unique=False)
    op.create_index(op.f("ix_feedback_org_id"), "feedback", ["org_id"], unique=False)
    op.create_table(
        "mcp_invocation",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("caller_trust_tier", sa.SmallInteger(), nullable=False),
        sa.Column("denied_reason", sa.Text(), nullable=True),
        sa.Column("offending_bundle_item_id", sa.UUID(), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending_approval', 'approved', 'denied', 'succeeded', 'failed')",
            name=op.f("ck_mcp_invocation_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["app_user.id"],
            name=op.f("fk_mcp_invocation_approved_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_message.id"],
            name=op.f("fk_mcp_invocation_message_id_chat_message"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["offending_bundle_item_id"],
            ["bundle_item.id"],
            name=op.f("fk_mcp_invocation_offending_bundle_item_id_bundle_item"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_mcp_invocation_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["mcp_tool.id"],
            name=op.f("fk_mcp_invocation_tool_id_mcp_tool"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_mcp_invocation_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_invocation")),
    )
    op.create_index(op.f("ix_mcp_invocation_org_id"), "mcp_invocation", ["org_id"], unique=False)
    op.create_index(
        "ix_mcp_invocation_org_id_created_at",
        "mcp_invocation",
        ["org_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_mcp_invocation_status_created_at",
        "mcp_invocation",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending_approval'"),
    )
    op.create_table(
        "message_citation",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("marker", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("memory_id", sa.UUID(), nullable=True),
        sa.Column("quoted_text", sa.Text(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunk.id"],
            name=op.f("fk_message_citation_chunk_id_chunk"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_message_citation_document_id_document"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memory.id"],
            name=op.f("fk_message_citation_memory_id_memory"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_message.id"],
            name=op.f("fk_message_citation_message_id_chat_message"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_message_citation_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_citation")),
        sa.UniqueConstraint("message_id", "marker", name="uq_message_citation_message_id_marker"),
    )
    op.create_index(
        op.f("ix_message_citation_org_id"), "message_citation", ["org_id"], unique=False
    )
    op.create_index(
        "ix_message_citation_org_id_message_id",
        "message_citation",
        ["org_id", "message_id"],
        unique=False,
    )
    op.create_table(
        "sql_run",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("datasource_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("generated_sql", sa.Text(), nullable=False),
        sa.Column("verdict", sa.String(length=48), nullable=False),
        sa.Column("verdict_detail", sa.Text(), nullable=True),
        sa.Column(
            "authorized_tables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "denied_tables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("executed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("truncated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('allowed', 'rejected_write', 'rejected_unauthorized_table', 'rejected_unparseable', 'rejected_too_complex')",
            name=op.f("ck_sql_run_verdict_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["sql_datasource.id"],
            name=op.f("fk_sql_run_datasource_id_sql_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_message.id"],
            name=op.f("fk_sql_run_message_id_chat_message"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_sql_run_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sql_run")),
        sa.UniqueConstraint("message_id", "attempt", name="uq_sql_run_message_id_attempt"),
    )
    op.create_index(op.f("ix_sql_run_org_id"), "sql_run", ["org_id"], unique=False)
    op.create_index(
        "ix_sql_run_org_id_created_at", "sql_run", ["org_id", "created_at"], unique=False
    )
    op.create_index("ix_sql_run_org_id_verdict", "sql_run", ["org_id", "verdict"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_sql_run_org_id_verdict", table_name="sql_run")
    op.drop_index("ix_sql_run_org_id_created_at", table_name="sql_run")
    op.drop_index(op.f("ix_sql_run_org_id"), table_name="sql_run")
    op.drop_table("sql_run")
    op.drop_index("ix_message_citation_org_id_message_id", table_name="message_citation")
    op.drop_index(op.f("ix_message_citation_org_id"), table_name="message_citation")
    op.drop_table("message_citation")
    op.drop_index(
        "ix_mcp_invocation_status_created_at",
        table_name="mcp_invocation",
        postgresql_where=sa.text("status = 'pending_approval'"),
    )
    op.drop_index("ix_mcp_invocation_org_id_created_at", table_name="mcp_invocation")
    op.drop_index(op.f("ix_mcp_invocation_org_id"), table_name="mcp_invocation")
    op.drop_table("mcp_invocation")
    op.drop_index(op.f("ix_feedback_org_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_message_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_bookmark_user_id"), table_name="bookmark")
    op.drop_index(op.f("ix_bookmark_org_id"), table_name="bookmark")
    op.drop_table("bookmark")
    op.drop_index("ix_chat_message_org_id_session_id_ordinal", table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_org_id"), table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_index("ix_bundle_item_org_id_bundle_id_position", table_name="bundle_item")
    op.drop_index(op.f("ix_bundle_item_org_id"), table_name="bundle_item")
    op.drop_table("bundle_item")
    op.drop_index(op.f("ix_ingest_job_event_org_id"), table_name="ingest_job_event")
    op.drop_index("ix_ingest_job_event_job_id_occurred_at", table_name="ingest_job_event")
    op.drop_table("ingest_job_event")
    op.drop_index("ix_context_bundle_org_id_created_at", table_name="context_bundle")
    op.drop_index(op.f("ix_context_bundle_org_id"), table_name="context_bundle")
    op.drop_table("context_bundle")
    op.drop_index(
        "ix_chunk_embedding_vector_hnsw",
        table_name="chunk_embedding",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
    )
    op.drop_index(
        "ix_chunk_embedding_org_id_is_current",
        table_name="chunk_embedding",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(op.f("ix_chunk_embedding_org_id"), table_name="chunk_embedding")
    op.drop_table("chunk_embedding")
    op.drop_index(
        "ix_memory_embedding_vector_hnsw",
        table_name="memory_embedding",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
    )
    op.drop_index(
        "ix_memory_embedding_org_id_is_live",
        table_name="memory_embedding",
        postgresql_where=sa.text("is_live"),
    )
    op.drop_index(op.f("ix_memory_embedding_org_id"), table_name="memory_embedding")
    op.drop_table("memory_embedding")
    op.drop_index(op.f("ix_memory_edge_src_id"), table_name="memory_edge")
    op.drop_index(op.f("ix_memory_edge_org_id"), table_name="memory_edge")
    op.drop_index("ix_memory_edge_dst_id_kind", table_name="memory_edge")
    op.drop_table("memory_edge")
    op.drop_index("ix_ingest_job_status_heartbeat_at", table_name="ingest_job")
    op.drop_index("ix_ingest_job_org_id_created_at", table_name="ingest_job")
    op.drop_index(op.f("ix_ingest_job_org_id"), table_name="ingest_job")
    op.drop_table("ingest_job")
    op.drop_index(
        "ix_chunk_text_trgm",
        table_name="chunk",
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    )
    op.drop_index("ix_chunk_org_id_document_id", table_name="chunk")
    op.drop_index(op.f("ix_chunk_org_id"), table_name="chunk")
    op.drop_table("chunk")
    op.drop_index("ix_chat_session_org_id_user_id_last_message_at", table_name="chat_session")
    op.drop_index(op.f("ix_chat_session_org_id"), table_name="chat_session")
    op.drop_table("chat_session")
    op.drop_index(op.f("ix_user_tag_user_id"), table_name="user_tag")
    op.drop_index(op.f("ix_user_tag_tag_id"), table_name="user_tag")
    op.drop_index(op.f("ix_user_tag_org_id"), table_name="user_tag")
    op.drop_table("user_tag")
    op.drop_index("ix_session_user_id_expires_at", table_name="session")
    op.drop_index(op.f("ix_session_org_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_role_binding_user_id"), table_name="role_binding")
    op.drop_index(op.f("ix_role_binding_org_id"), table_name="role_binding")
    op.drop_table("role_binding")
    op.drop_index(
        "uq_prompt_version_one_active",
        table_name="prompt_version",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_prompt_version_org_id"), table_name="prompt_version")
    op.drop_table("prompt_version")
    op.drop_index("ix_memory_valid_range", table_name="memory", postgresql_using="gist")
    op.drop_index(
        "ix_memory_org_id_subject_id_predicate",
        table_name="memory",
        postgresql_where=sa.text("retracted_at IS NULL"),
    )
    op.drop_index("ix_memory_org_id_status_recorded_at", table_name="memory")
    op.drop_index(op.f("ix_memory_org_id"), table_name="memory")
    op.drop_table("memory")
    op.drop_index(op.f("ix_mcp_grant_user_id"), table_name="mcp_grant")
    op.drop_index(op.f("ix_mcp_grant_org_id"), table_name="mcp_grant")
    op.drop_table("mcp_grant")
    op.drop_index(op.f("ix_mcp_credential_user_id"), table_name="mcp_credential")
    op.drop_index(op.f("ix_mcp_credential_org_id"), table_name="mcp_credential")
    op.drop_table("mcp_credential")
    op.drop_index(op.f("ix_folder_user_id"), table_name="folder")
    op.drop_index(op.f("ix_folder_org_id"), table_name="folder")
    op.drop_table("folder")
    op.drop_index("ix_document_org_id_lineage_key", table_name="document")
    op.drop_index("ix_document_org_id_collection_id_status", table_name="document")
    op.drop_index(op.f("ix_document_org_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_api_key_user_id"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_org_id"), table_name="api_key")
    op.drop_table("api_key")
    op.drop_index("ix_sql_schema_object_org_id_datasource_id", table_name="sql_schema_object")
    op.drop_index(op.f("ix_sql_schema_object_org_id"), table_name="sql_schema_object")
    op.drop_table("sql_schema_object")
    op.drop_index("ix_mcp_tool_org_id_server_id", table_name="mcp_tool")
    op.drop_index(op.f("ix_mcp_tool_org_id"), table_name="mcp_tool")
    op.drop_table("mcp_tool")
    op.drop_index(op.f("ix_glossary_term_org_id"), table_name="glossary_term")
    op.drop_table("glossary_term")
    op.drop_index("ix_app_user_org_id_external_subject", table_name="app_user")
    op.drop_index(op.f("ix_app_user_org_id"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_index(op.f("ix_tag_org_id"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ix_subject_org_id"), table_name="subject")
    op.drop_table("subject")
    op.drop_index(op.f("ix_sql_datasource_org_id"), table_name="sql_datasource")
    op.drop_table("sql_datasource")
    op.drop_index(op.f("ix_role_org_id"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_prompt_org_id"), table_name="prompt")
    op.drop_table("prompt")
    op.drop_index(op.f("ix_mcp_server_org_id"), table_name="mcp_server")
    op.drop_table("mcp_server")
    op.drop_index("ix_inference_call_org_id_occurred_at", table_name="inference_call")
    op.drop_index("ix_inference_call_org_id_model_occurred_at", table_name="inference_call")
    op.drop_index(op.f("ix_inference_call_org_id"), table_name="inference_call")
    op.drop_table("inference_call")
    op.drop_index(op.f("ix_identity_provider_org_id"), table_name="identity_provider")
    op.drop_table("identity_provider")
    op.drop_index("ix_context_plan_org_id_created_at", table_name="context_plan")
    op.drop_index(op.f("ix_context_plan_org_id"), table_name="context_plan")
    op.drop_table("context_plan")
    op.drop_index(op.f("ix_collection_org_id"), table_name="collection")
    op.drop_table("collection")
    op.drop_index("ix_audit_log_org_id_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_org_id_action_occurred_at", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_actor_id_occurred_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("org")
